In [1]:
import pandas as pd
import numpy as np
import pprint
p = r"E:\my_proj\fog_recognition\pre_fog_v3\resources\fixed_data\TidyData\formed_signal\20161223_1_1.csv"
df = pd.read_csv(p)

In [ ]:
array = numpy.asarray(df.iloc[0:10, 0:2])

array([[ 185, 1009],
       [ 183, 1003],
       [ 177, 1011],
       [ 179, 1008],
       [ 184, 1010],
       [ 185, 1003],
       [ 174, 1005],
       [ 183, 1004],
       [ 180, 1009],
       [ 180, 1007]], dtype=int64)

In [66]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer
transformer = FunctionTransformer(np.log1p, validate=True)
X = np.array([[0, 1], [2, 3]])
transformer.transform(df.iloc[0:10, 0:2])


array([[5.22574667, 6.91770561],
       [5.21493576, 6.9117473 ],
       [5.18178355, 6.91968385],
       [5.19295685, 6.91671502],
       [5.22035583, 6.91869522],
       [5.22574667, 6.9117473 ],
       [5.16478597, 6.91373735],
       [5.21493576, 6.91274282],
       [5.19849703, 6.91770561],
       [5.19849703, 6.91572345]])

In [20]:
transformer.transform(df.iloc[0:10, 0:2])


array([[ 5.19933758,  0.5894558 ],
       [ 0.28221615, -5.19933758],
       [-1.22064035,  5.19933758],
       [-0.76470967,  0.1397103 ],
       [ 0.76470967,  1.22064035],
       [ 5.19933758, -5.19933758],
       [-5.19933758, -0.4307273 ],
       [ 0.28221615, -0.76470967],
       [-0.28221615,  0.5894558 ],
       [-0.28221615, -0.1397103 ]])

In [26]:
pprint.pprint(df.head())

array([[ 5.19933758,  0.5894558 ],
       [ 0.28221615, -5.19933758],
       [-1.22064035,  5.19933758],
       [-0.76470967,  0.1397103 ],
       [ 0.76470967,  1.22064035],
       [ 5.19933758, -5.19933758],
       [-5.19933758, -0.4307273 ],
       [ 0.28221615, -0.76470967],
       [-0.28221615,  0.5894558 ],
       [-0.28221615, -0.1397103 ]])

In [28]:
from sklearn import preprocessing
df1=df.iloc[0:10,0:2]
quantile_transformer = preprocessing.QuantileTransformer(output_distribution='normal', random_state=0)
quantile_transformer.fit_transform(df1)

array([[ 5.19933758,  0.5894558 ],
       [ 0.28221615, -5.19933758],
       [-1.22064035,  5.19933758],
       [-0.76470967,  0.1397103 ],
       [ 0.76470967,  1.22064035],
       [ 5.19933758, -5.19933758],
       [-5.19933758, -0.4307273 ],
       [ 0.28221615, -0.76470967],
       [-0.28221615,  0.5894558 ],
       [-0.28221615, -0.1397103 ]])

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris = load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
quantile_transformer = preprocessing.QuantileTransformer(random_state=0)
X_train_trans = quantile_transformer.fit_transform(X_train)
X_test_trans = quantile_transformer.transform(X_test)
rtn = np.percentile(X_train[:, 0], [0, 25, 50, 75, 100]) 
print('原始数据的分位数:', rtn)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A100_accelerometer_x</th>
      <th>A100_accelerometer_y</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>185</td>
      <td>1009</td>
    </tr>
    <tr>
      <th>1</th>
      <td>183</td>
      <td>1003</td>
    </tr>
    <tr>
      <th>2</th>
      <td>177</td>
      <td>1011</td>
    </tr>
    <tr>
      <th>3</th>
      <td>179</td>
      <td>1008</td>
    </tr>
    <tr>
      <th>4</th>
      <td>184</td>
      <td>1010</td>
    </tr>
    <tr>
      <th>5</th>
      <td>185</td>
      <td>1003</td>
    </tr>
    <tr>
      <th>6</th>
      <td>174</td>
      <td>1005</td>
    </tr>
    <tr>
      <th>7</th>
      <td>183</td>
      <td>1004</td>
    </tr>
    <tr>
      <th>8</th>
      <td>180</td>
      <td>1009</td>
    </tr>
    <tr>
      <th>9</th>
      <td>180</td>
      <td>1007</td>
    </tr>
  </tbody>
</table>
</div>

In [18]:
np.log1p(185),np.log1p(1009)

(5.225746673713202, 6.917705609835305)

In [65]:
from scipy import stats
from matplotlib import pyplot as plt
stats.norm.cdf(df.iloc[0:10,0],loc=180, scale=4)

array([0.89435023, 0.77337265, 0.22662735, 0.40129367, 0.84134475,
       0.89435023, 0.0668072 , 0.77337265, 0.5       , 0.5       ])

In [14]:
stats.norm.fit(df.iloc[0:100,0])

(180.84, 3.981758405528894)

In [56]:
plt.hist(stats.norm.cdf(df.iloc[0:10000,0],loc=180, scale=4))
plt.show()

In [16]:
plt.hist(df.iloc[0:100,0], density=True, histtype='stepfilled', alpha=0.2)
plt.show()

In [22]:
from sklearn import preprocessing
qt = preprocessing.QuantileTransformer(output_distribution='normal', random_state=0)

In [38]:
pd.DataFrame(qt.fit_transform(df.iloc[:, [2]])).to_csv('debug_1.csv',index=False)

In [34]:
plt.hist(df.iloc[:, [2]])
plt.show()

In [44]:
plt.hist(qt.fit_transform(df.iloc[:, [2]]),bins=100)
plt.show()
#plt.hist()

In [45]:
df2=pd.read_clipboard()

In [50]:
plt.hist(preprocessing.scale(df2),bins=30)
plt.show()

In [53]:
plt.hist(df2.values,bins=30)
plt.show()

In [ ]:

from sklearn.preprocessing import FunctionTransformer


1011

In [70]:
ar = df.iloc[0:10, 0:2].values


1011

1011

In [ ]:

transformer = FunctionTransformer(np.log1p, validate=True)


1011

In [94]:
from sklearn.preprocessing import FunctionTransformer

def filter_data(x: numpy.ndarray)->numpy.ndarray:
    from typing import List
    import pandas
    def between_range(array: numpy.ndarray)-> List[float]:
        interval = pandas.Interval(numpy.quantile(array, 0.005), numpy.quantile(array, 0.995), closed='both')
        print('-->',interval)
        return list(map(lambda y: y if y in interval else None, array))
    return pandas.DataFrame(data=x).apply(lambda it: between_range(it), axis=0).values

ft = FunctionTransformer(filter_data,validate=False)

In [95]:
ft.transform(df.iloc[0:10, 0:4])

--> [174.135, 185.0]
--> [174.135, 185.0]
--> [1003.0, 1010.955]
--> [155.04500000000002, 170.73]
--> [-83.28, 59.64]


array([[ 185., 1009.,  159.,  -40.],
       [ 183., 1003.,  157.,  -22.],
       [ 177.,   nan,   nan,   -4.],
       [ 179., 1008.,  160.,   52.],
       [ 184., 1010.,  165.,   nan],
       [ 185., 1003.,  156.,  -16.],
       [  nan, 1005.,  161.,  -38.],
       [ 183., 1004.,  163.,   nan],
       [ 180., 1009.,  156.,   42.],
       [ 180., 1007.,   nan,  -68.]])

In [ ]:
a_string = "This is a global variable"
def foo():
     print(locals(),globals())
#print(globals()) # doctest: +ELLIPSIS

foo() # 2


In [14]:

def outer():
     def inner():
         print("Inside inner")
     return inner # 1
 
foo = outer() #2
foo.__closure__

In [15]:
def outer():
     x = 1
     def inner():
         print(x) # 1
     return inner
foo = outer()
foo.__closure__

(<cell at 0x0000000016816AC8: int object at 0x0000000053FD6DE0>,)

In [2]:
from sklearn.model_selection import LeaveOneGroupOut
import numpy as np
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([1, 2, 1, 2])
groups = np.array([1, 1, 2, 2])
logo = LeaveOneGroupOut()
logo.get_n_splits(X, y, groups)

logo.get_n_splits(groups=groups) # 'groups' is always required

print(logo)

for train_index, test_index in logo.split(X, y, groups):
   print("TRAIN:", train_index, "TEST:", test_index)
   X_train, X_test = X[train_index], X[test_index]
   y_train, y_test = y[train_index], y[test_index]
   print(X_train, X_test, y_train, y_test)


LeaveOneGroupOut()
TRAIN: [2 3] TEST: [0 1]
[[5 6]
 [7 8]] [[1 2]
 [3 4]] [1 2] [1 2]
TRAIN: [0 1] TEST: [2 3]
[[1 2]
 [3 4]] [[5 6]
 [7 8]] [1 2] [1 2]


In [ ]:
def yd(n=6):
    for i in range(n):
        yield i